# This configuration file assumes that it is in the bigbang
# directory (the same folder as .gitignore, requirements.txt,
# etc.) The given paths are to be appended to the filepath of 
# the bigbang directory, which is calculated from the filepath
# of the config.yml file. For example, if a path is 
# "archives/sample-git-repos", and the filepath of this file is
# "~/folder/other/bigbang/config/config.yml" the full interpretation 
# of it should be "~/folder/other/bigbang/archives/sample-git-repos".
# Note that "config/config.yml" was taken out. This will be a
# manual process.

# PATHS. 
# For Configuration to work properly, paths need to have "path"
# in their keyword.
# NOTE: BE CAFEFUL NOT TO PUT 'path' IN OTHER ATTRIBUTE NAMES
repo_path : "archives/sample-git-repos/"
mail_path : "archives/"
urls_path : "examples/"


# REGEX
# These are certain important regular expressions
# TODO: They are not completely standardized or stable yet. They do not yet work
git_url_to_name_rgx: '([^/]*)(\\.git$)'
file_to_name_rgx : '.*\/(.*)'
